// INCLUDE PACKAGES NEEDED FOR THIS APPLICATION
const inquirer = require("inquirer");
const mysql = require("mysql");
const cTable = require("console.table");

// SET UP MYSQL CONNECTION

// Note - LEAVE EMPTY STRING FOR YOUR PW

// MAKE CONNECTION

// VIEW ALL EMPLOYEES IN EMPLOYEE TABLE

// ADD EMPLOYEE TO EMPLOYEE TABLE

// UPDATE EMPLOYEES ROLE

// REMOVE EMPLOYEE BY THEIR NAME FROM EMPLOYEE TABLE

// VIEW ALL ROLES IN ROLE TABLE

// ADD ROLE TO ROLE TABLE

// REMOVE SELECTED ROLE BY NAME FROM ROLE TABLE

// VIEW ALL DEPARTMENTS IN DEPARTMENT TABLE

// ADD DEPARTMENT TO DEPARTMENT TABLE

// REMOVE SELECTED DEPARTMENT BY NAME FROM DEPARTMENT TABLE

// EMPTY ARRAY

// FUNCTION THAT FETCHES CURRENT ROLE TITLES

// FUNCTION THAT FETCHES NAMES OF CURRENT EMPLOYEES IN DB

// EMPTY ARRAY







